In [1]:
import pandas as pd

In [3]:
from pybtex.database.input import bibtex

#open a bibtex file
parser = bibtex.Parser()
bibdata = parser.parse_file("anthology+abstracts.bib")
lst_ant = []

i= 0
#loop through the individual references
for bib_id in bibdata.entries:
    
    b = bibdata.entries[bib_id].fields
    try:      
        lst_ant.append(b)
        i +=1  
        
        
        # change these lines to create a SQL insert
#         print(b["title"])
#         print(b["journal"])
#         print(b["year"])
        #deal with multiple authors
#         for author in bibdata.entries[bib_id].persons["author"]:
#             print(author.first(), author.last())
    # field may not exist for a reference
    except(KeyError):
        continue

In [ ]:
lst_ant[3]#['title']

In [ ]:
# lst_ant[3]['title'].replace('}', '').replace('{', '')

In [4]:
df = pd.DataFrame(lst_ant)
df.head()

,ISBN,abstract,address,booktitle,doi,journal,language,month,note,number,pages,publisher,title,url,volume,year
0,NaN,NaN,"(Hybrid) Dublin, Ireland, and Virtual",NaN,NaN,NaN,NaN,May,NaN,NaN,NaN,Association for Computational Linguistics,Proceedings of the 2nd Workshop on Deriving In...,https://aclanthology.org/2022.wit-1.0,NaN,2022
1,NaN,We advance the state-of-the-art in unsupervise...,"(Hybrid) Dublin, Ireland, and Virtual",Proceedings of the 2nd Workshop on Deriving In...,10.18653/v1/2022.wit-1.1,NaN,NaN,May,NaN,NaN,1--9,Association for Computational Linguistics,Unsupervised Abstractive Dialogue Summarizatio...,https://aclanthology.org/2022.wit-1.1,NaN,2022
2,NaN,With millions of documented recoveries from CO...,"(Hybrid) Dublin, Ireland, and Virtual",Proceedings of the 2nd Workshop on Deriving In...,10.18653/v1/2022.wit-1.2,NaN,NaN,May,NaN,NaN,10--19,Association for Computational Linguistics,An Interactive Analysis of User-reported Long ...,https://aclanthology.org/2022.wit-1.2,NaN,2022
3,NaN,Classification of posts in social media such a...,"(Hybrid) Dublin, Ireland, and Virtual",Proceedings of the 2nd Workshop on Deriving In...,10.18653/v1/2022.wit-1.3,NaN,NaN,May,NaN,NaN,20--24,Association for Computational Linguistics,Bi-Directional Recurrent Neural Ordinary Diffe...,https://aclanthology.org/2022.wit-1.3,NaN,2022
4,NaN,NaN,"Dublin, Ireland",NaN,NaN,NaN,NaN,May,NaN,NaN,NaN,Association for Computational Linguistics,Proceedings of the 12th Workshop on Computatio...,https://aclanthology.org/2022.wassa-1.0,NaN,2022

In [25]:
# df['title'] = df['title'].str.replace('}', '').str.replace('{', '')
# df.title

C:\Users\20193635\AppData\Local\Temp/ipykernel_11008/111540803.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['title'] = df['title'].str.replace('}', '').str.replace('{', '')

0        Proceedings of the 5th Workshop on Online Abus...
1        Exploiting Auxiliary Data for Offensive Langua...
2        Modeling Profanity and Hate Speech in Social M...
3        HateBERT: Retraining BERT for Abusive Language...
4        Memes in the Wild: Assessing the Generalizabil...
                               ...
74515    Teaching foreign languages or MT and language ...
74516    Machine techniques for index searching and for...
74517                            Transcript of discussions
74518       The first conference on mechanical translation
74519    The conference on mechanical translation held ...
Name: title, Length: 74520, dtype: object

In [6]:
df[['abstract','url']].describe()

       abstract                                          url
count     32425                                        76357
unique    32301                                        76351
top              https://aclanthology.org/2006.amta-panels.0
freq        109                                            2

In [10]:
abstract = df[['abstract','url']].dropna()

In [11]:
abstract

,abstract,url
1,We advance the state-of-the-art in unsupervise...,https://aclanthology.org/2022.wit-1.1
2,With millions of documented recoveries from CO...,https://aclanthology.org/2022.wit-1.2
3,Classification of posts in social media such a...,https://aclanthology.org/2022.wit-1.3
5,Authors of posts in social media communicate t...,https://aclanthology.org/2022.wassa-1.1
6,COVID-19 has disproportionately threatened min...,https://aclanthology.org/2022.wassa-1.2
...,...,...
76159,This paper deals with the problem of represent...,https://aclanthology.org/1963.earlymt-1.30
76160,It becomes more and more evident that successf...,https://aclanthology.org/1963.earlymt-1.31
76161,Establishing the grammatical description of a ...,https://aclanthology.org/1963.earlymt-1.32
76162,A grammar based upon a conventional morphemic ...,https://aclanthology.org/1963.earlymt-1.33
76163,We used to think that the output of a translat...,https://aclanthology.org/1963.earlymt-1.34

In [13]:
df.describe()

,ISBN,abstract,address,booktitle,doi,journal,language,month,note,number,pages,publisher,title,url,volume,year
count,1405,32425,68596,71686,29649,2585,3037,68301,200,1844,59664,65387,76357,76357,2366,76357
unique,37,32301,401,2263,29644,3,5,177,83,6,23014,112,75427,76351,48,61
top,979-10-95546-34-4,,Online,Proceedings of the 12th Language Resources and...,10.18653/v1/W15-43,Computational Linguistics,French,June,Microfiche 79,1,1--10,Association for Computational Linguistics,Advertisements,https://aclanthology.org/2006.amta-panels.0,9,2020
freq,896,109,6818,895,3,1736,1440,11300,14,470,239,41667,59,2,126,7140

In [15]:
len(df), len(abstract)

(76357, 32425)

# downloading pdf

In [12]:
# import urllib
# urllib.request.urlretrieve(df['url'][1]+'.pdf', "pdf\Anthology.pdf")

('pdf\\Anthology.pdf', <http.client.HTTPMessage at 0x1b705b93d90>)

# save df

In [17]:
# df.to_csv('anthology_table.csv')
abstract.to_csv('abs_table.csv', index=False)